// Sample products data with more items for pagination
export const sampleProducts = [
  {
    id: 1,
    name: 'Refurbished MacBook Pro',
    description: 'High-performance laptop refurbished to like-new condition with 1-year warranty',
    price: 899,
    originalPrice: 1299,
    category: 'Electronics',
    subcategory: 'Laptops',
    brand: 'Apple',
    image: '/image/1.jpg',
    condition: 'Like New',
    seller: 'TechStore',
    rating: 4.8,
    reviews: 45,
    inStock: true,
    featured: true
  },
  {
    id: 2,
    name: 'Vintage Oak Dining Table',
    description: 'Beautiful solid oak dining table, restored and eco-friendly',
    price: 450,
    originalPrice: 650,
    category: 'Furniture',
    subcategory: 'Desks',
    brand: 'Generic',
    image: '/image/2.jpg',
    condition: 'Excellent',
    seller: 'FurnitureRevive',
    rating: 4.9,
    reviews: 23,
    inStock: true,
    featured: true
  },  {
    id: 3,
    name: 'Designer Winter Jacket',
    description: 'Pre-loved designer jacket in excellent condition, perfect for winter',
    price: 89,
    originalPrice: 250,
    category: 'Clothing',
    subcategory: "Men's Wear",
    brand: 'Nike',
    image: '/image/3.png',
    condition: 'Very Good',
    seller: 'StyleSecond',
    rating: 4.7,
    reviews: 18,
    inStock: true,
    featured: false
  },
  {
    id: 4,
    name: 'iPhone 12 Pro',
    description: 'Unlocked iPhone 12 Pro in great condition with original box',
    price: 650,
    originalPrice: 999,
    category: 'Electronics',
    subcategory: 'Phones',
    brand: 'Apple',
    image: '/image/4.jpg',
    condition: 'Good',
    seller: 'MobileHub',
    rating: 4.6,
    reviews: 67,
    inStock: true,
    featured: false
  },
  {
    id: 5,
    name: 'Ergonomic Office Chair',
    description: 'Comfortable office chair with adjustable height and lumbar support',
    price: 199,
    originalPrice: 350,
    category: 'Furniture',
    subcategory: 'Chairs',
    brand: 'IKEA',
    image: '/image/5.png',
    condition: 'Like New',
    seller: 'OfficeSpace',
    rating: 4.5,
    reviews: 32,
    inStock: true,
    featured: false
  },
  {
    id: 6,
    name: 'Mountain Bike',
    description: 'Well-maintained mountain bike perfect for outdoor adventures',
    price: 320,
    originalPrice: 600,
    category: 'Sports & Recreation',
    subcategory: 'Bicycles',
    brand: 'Generic',
    image: '/image/bike1.jpg',
    condition: 'Very Good',
    seller: 'BikeWorld',
    rating: 4.4,
    reviews: 28,
    inStock: true,
    featured: true
  },
  {
    id: 7,
    name: 'Cookbook Collection',
    description: 'Set of 5 popular cookbooks in excellent condition',
    price: 45,
    originalPrice: 80,
    category: 'Books',
    subcategory: 'Reference',
    brand: 'Generic',
    image: '/image/books1.jpg',
    condition: 'Excellent',
    seller: 'BookNook',
    rating: 4.8,
    reviews: 15,
    inStock: true,
    featured: false
  },
  {
    id: 8,
    name: 'Wireless Headphones',
    description: 'Premium noise-cancelling wireless headphones',
    price: 150,
    originalPrice: 300,
    category: 'Electronics',
    subcategory: 'Audio',
    brand: 'Sony',
    image: '/image/headphones1.jpg',
    condition: 'Like New',
    seller: 'AudioTech',
    rating: 4.7,
    reviews: 52,
    inStock: true,
    featured: false
  },
  {
    id: 9,
    name: "Gaming Headset",
    description: "Professional gaming headset with surround sound",
    price: 75,
    originalPrice: 150,
    category: "Electronics",
    subcategory: "Audio",
    brand: "Sony",
    image: "/image/1.jpg",
    condition: "Very Good",
    seller: "GameZone",
    rating: 4.3,
    reviews: 89,
    inStock: true,
    featured: false,
  },
  {
    id: 10,
    name: "Office Chair",
    description: "Ergonomic office chair with lumbar support",
    price: 180,
    originalPrice: 350,
    category: "Furniture",
    subcategory: "Chairs",
    brand: "Generic",
    image: "/image/2.jpg",
    condition: "Excellent",
    seller: "OfficeSupply",
    rating: 4.6,
    reviews: 41,
    inStock: true,
    featured: false,
  },
  {
    id: 11,
    name: "Running Shoes",
    description: "High-quality running shoes, barely used",
    price: 65,
    originalPrice: 120,
    category: "Clothing",
    subcategory: "Shoes",
    brand: "Nike",
    image: "/image/3.png",
    condition: "Like New",
    seller: "SportsWear",
    rating: 4.7,
    reviews: 25,
    inStock: true,
    featured: false,
  },
  {
    id: 12,
    name: "Wireless Mouse",
    description: "Ergonomic wireless mouse for productivity",
    price: 35,
    originalPrice: 60,
    category: "Electronics",
    subcategory: "Computers",
    brand: "Generic",
    image: "/image/4.jpg",
    condition: "Good",
    seller: "TechDeals",
    rating: 4.2,
    reviews: 156,
    inStock: true,
    featured: false,
  },
];
